# Generated by Django 2.0 on 2018-04-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('artistic_name', models.CharField(max_length=256)),
                ('picture_url', models.URLField()),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
