# Generated by Django 2.1.1 on 2019-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20190217_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop')], default='rock', max_length=255),
            preserve_default=False,
        ),
    ]
