# Generated by Django 2.0 on 2018-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20181006_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(choices=[('soul', 'soul'), ('rock', 'rock'), ('pop', 'pop')], max_length=255, null=True),
        ),
    ]
